name: Linux Self Hosted Workflows

on: push

jobs:
  build:
    runs-on:
      - self-hosted
      - linux

    steps:
      - name: Display Message
        run: echo "Running on Linux Self-Hosted Runner"
